language: android

sudo: false

jdk: 
  - oraclejdk8

env:
  matrix:
    - ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a

# http://docs.travis-ci.com/user/caching/
cache:
  gradlew: true
  gradle: true
  directories:
    - $HOME/.gradle
    - $HOME/.m2
  
before_cache:  
  # cleanup a little for better caching reuse
  - rm -rf $HOME/.gradle/caches/2.4/scripts
  - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/daemon

# ask travic ci to download all revisions, we use revisions for version defining
git:
  depth: 10000
  
# list of available components https://github.com/travis-ci/travis-ci/issues/2301
android:
  components:
    - platform-tools
    - platform-tools-preview
    - build-tools-23.0.0-preview
    - build-tools-22.0.1
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - android-22
  licenses:
    - '.+'

before_install:
  # display list of all possible components
  - android list sdk --no-ui --all --extended | grep -E '^id:' | awk -F '"' '{$1=""; print $2}'
  # display list of installed emulators
  - android list targets | grep -e 'id:' -e 'Tag'
  # make scripts executable for linux CI
  - chmod +x gradlew

install:
  - true

before_script:
  # Create and start emulator
  #- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  #- emulator -avd test -no-skin -no-audio -no-window &
  #- adb wait-for-device
  #- adb shell input keyevent 82 &

branches:
  only:
    - master

script:
  # Execute Unit tests for all modules, generate report for library
  - ./gradlew test :binder:generateJacocoReportDebug --console=plain
  # Espresso/emulator tests
  # - ./gradlew connectedAndroidTest --console=plain

after_success:
  # Coverage report
  - ./gradlew :binder:coveralls

notifications:
  email: false
